M48
; DRILL file {KiCad (6.0.1-0)} date Monday, 28 March 2022 at 18:36:08
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-28T18:36:08+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X117.0Y-75.0
X117.0Y-103.0
X145.0Y-75.0
X145.0Y-103.0
T0
M30
